### ISSUE TITLE
调用人脸识别出错

### ISSUE THREAD

**Issue by junbao520** [View12138/ViewFaceCoreDemo#2]
![image](https://user-images.githubusercontent.com/20721833/112706627-7e6fb280-8ee0-11eb-9f42-31403c480500.png)

您好，请问下这个是这样调用的么？看你的API 提取特征值的方法就是这样，但是报错了，能否帮忙看看？

**Comment by View12138** [comment]
所有模型是否都下载了?

**Comment by junbao520** [comment]
问题解决了。所有模型都下载了。


人脸识别模式 =Light 会报截图错误
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; =Normal 可以正常运行！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "View12138/ViewFaceCoreDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [View12138/ViewFaceCoreDemo] 调用人脸识别出错 (#2)





 
所有模型是否都下载了?
